"""empty message

Revision ID: 16f169a906b4
Revises: 409ebb6128fd
Create Date: 2022-11-05 19:48:42.684074

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '16f169a906b4'
down_revision = '409ebb6128fd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('solicitud', sa.Column('fecha_inicial', sa.Date(), nullable=True))
    op.add_column('solicitud', sa.Column('fecha_fin', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('solicitud', 'fecha_fin')
    op.drop_column('solicitud', 'fecha_inicial')
    # ### end Alembic commands ###
