"""empty message

Revision ID: 269ed9fde336
Revises: 7b341695f43f
Create Date: 2022-10-25 02:39:15.113878

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '269ed9fde336'
down_revision = '7b341695f43f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cuidadores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=250), nullable=False),
    sa.Column('password', sa.String(length=250), nullable=False),
    sa.Column('nombre', sa.String(length=250), nullable=False),
    sa.Column('apellido', sa.String(length=250), nullable=False),
    sa.Column('telefono', sa.String(length=250), nullable=False),
    sa.Column('ubicacion', sa.String(length=250), nullable=False),
    sa.Column('tipo_de_mascota', sa.String(length=250), nullable=False),
    sa.Column('cantidad_de_mascotas', sa.String(length=250), nullable=False),
    sa.Column('imagen', sa.String(length=250), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('user', sa.Column('nombre', sa.String(length=250), nullable=False))
    op.add_column('user', sa.Column('apellido', sa.String(length=250), nullable=False))
    op.add_column('user', sa.Column('telefono', sa.String(length=250), nullable=False))
    op.add_column('user', sa.Column('salt', sa.String(length=250), nullable=False))
    op.add_column('user', sa.Column('imagen', sa.String(length=250), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'imagen')
    op.drop_column('user', 'salt')
    op.drop_column('user', 'telefono')
    op.drop_column('user', 'apellido')
    op.drop_column('user', 'nombre')
    op.drop_table('cuidadores')
    # ### end Alembic commands ###
