"""empty message

Revision ID: 3611d88f87aa
Revises: 
Create Date: 2022-11-05 16:02:56.090524

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3611d88f87aa'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cliente',
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('hashed_password', sa.String(length=480), nullable=False),
    sa.Column('nombre', sa.String(length=250), nullable=False),
    sa.Column('apellido', sa.String(length=250), nullable=False),
    sa.Column('telefono', sa.String(length=250), nullable=False),
    sa.Column('salt', sa.String(length=250), nullable=False),
    sa.Column('imagen', sa.String(length=250), nullable=True),
    sa.Column('descripcion', sa.String(length=250), nullable=True),
    sa.Column('tipo_mascota', sa.String(length=250), nullable=False),
    sa.Column('cantidad_mascota', sa.String(length=250), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('cuidador',
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('hashed_password', sa.String(length=480), nullable=False),
    sa.Column('nombre', sa.String(length=250), nullable=False),
    sa.Column('apellido', sa.String(length=250), nullable=False),
    sa.Column('telefono', sa.String(length=250), nullable=False),
    sa.Column('salt', sa.String(length=250), nullable=False),
    sa.Column('imagen', sa.String(length=250), nullable=True),
    sa.Column('descripcion', sa.String(length=250), nullable=True),
    sa.Column('tipo_mascota', sa.String(length=250), nullable=False),
    sa.Column('cantidad_mascota', sa.String(length=250), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ubicacion', sa.String(length=250), nullable=False),
    sa.Column('precio_hora', sa.String(length=250), nullable=True),
    sa.Column('precio_dia', sa.String(length=250), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cuidador')
    op.drop_table('cliente')
    # ### end Alembic commands ###
