"""empty message

Revision ID: b3aafb696e6f
Revises: 
Create Date: 2022-10-27 20:47:08.471052

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b3aafb696e6f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cliente',
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('hashed_password', sa.String(length=480), nullable=False),
    sa.Column('nombre', sa.String(length=250), nullable=False),
    sa.Column('apellido', sa.String(length=250), nullable=False),
    sa.Column('telefono', sa.String(length=250), nullable=False),
    sa.Column('salt', sa.String(length=250), nullable=False),
    sa.Column('imagen', sa.String(length=250), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('cuidador',
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('hashed_password', sa.String(length=480), nullable=False),
    sa.Column('nombre', sa.String(length=250), nullable=False),
    sa.Column('apellido', sa.String(length=250), nullable=False),
    sa.Column('telefono', sa.String(length=250), nullable=False),
    sa.Column('salt', sa.String(length=250), nullable=False),
    sa.Column('imagen', sa.String(length=250), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ubicacion', sa.String(length=250), nullable=False),
    sa.Column('tipo_mascota', sa.String(length=250), nullable=False),
    sa.Column('cantidad_mascota', sa.String(length=250), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cuidador')
    op.drop_table('cliente')
    # ### end Alembic commands ###
