"""empty message

Revision ID: bda6715dfdeb
Revises: 3d0177914dd7
Create Date: 2022-10-26 03:40:01.790961

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bda6715dfdeb'
down_revision = '3d0177914dd7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cuidador', sa.Column('tipoMascota', sa.String(length=250), nullable=False))
    op.add_column('cuidador', sa.Column('cantidadMascota', sa.String(length=250), nullable=False))
    op.drop_column('cuidador', 'cantidad_de_mascotas')
    op.drop_column('cuidador', 'tipo_de_mascota')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cuidador', sa.Column('tipo_de_mascota', sa.VARCHAR(length=250), autoincrement=False, nullable=False))
    op.add_column('cuidador', sa.Column('cantidad_de_mascotas', sa.VARCHAR(length=250), autoincrement=False, nullable=False))
    op.drop_column('cuidador', 'cantidadMascota')
    op.drop_column('cuidador', 'tipoMascota')
    # ### end Alembic commands ###
